// flow-typed signature: 8c7815ca2009c2efcea04f19ceb99ecd
// flow-typed version: <<STUB>>/asar_v^0.12.3/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'asar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'asar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'asar/lib/asar' {
  declare module.exports: any;
}

declare module 'asar/lib/crawlfs' {
  declare module.exports: any;
}

declare module 'asar/lib/disk' {
  declare module.exports: any;
}

declare module 'asar/lib/filesystem' {
  declare module.exports: any;
}

declare module 'asar/lib/snapshot' {
  declare module.exports: any;
}

// Filename aliases
declare module 'asar/lib/asar.js' {
  declare module.exports: $Exports<'asar/lib/asar'>;
}
declare module 'asar/lib/crawlfs.js' {
  declare module.exports: $Exports<'asar/lib/crawlfs'>;
}
declare module 'asar/lib/disk.js' {
  declare module.exports: $Exports<'asar/lib/disk'>;
}
declare module 'asar/lib/filesystem.js' {
  declare module.exports: $Exports<'asar/lib/filesystem'>;
}
declare module 'asar/lib/snapshot.js' {
  declare module.exports: $Exports<'asar/lib/snapshot'>;
}
