// flow-typed signature: 8fe7265d2cc935a5c7c5c537f79ca01f
// flow-typed version: <<STUB>>/babel-preset-stage-0_v^6.22.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-stage-0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-stage-0' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-stage-0/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-stage-0/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-stage-0/lib/index'>;
}
