// flow-typed signature: 193df553037a89a455626046cdd7a069
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-classes_v^6.22.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-classes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-classes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-classes/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-es2015-classes/lib/lib/memoise-decorators' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-es2015-classes/lib/loose' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-es2015-classes/lib/vanilla' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-classes/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-classes/lib/index'>;
}
declare module 'babel-plugin-transform-es2015-classes/lib/lib/memoise-decorators.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-classes/lib/lib/memoise-decorators'>;
}
declare module 'babel-plugin-transform-es2015-classes/lib/loose.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-classes/lib/loose'>;
}
declare module 'babel-plugin-transform-es2015-classes/lib/vanilla.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-classes/lib/vanilla'>;
}
