// flow-typed signature: 3869cdef4640c961396fea65c84f0aa3
// flow-typed version: <<STUB>>/babel-plugin-dynamic-import-webpack_v^1.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-dynamic-import-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-dynamic-import-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-dynamic-import-webpack/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-dynamic-import-webpack/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-dynamic-import-webpack/lib/index'>;
}
