// flow-typed signature: feab0cb5e9afef63cd4e5beaaf5a025c
// flow-typed version: <<STUB>>/babel-plugin-tcomb_v^0.3.24/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-tcomb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-tcomb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-tcomb/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-tcomb/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-tcomb/lib/index'>;
}
