// flow-typed signature: 0588aa994e7738815e1932febcc8975d
// flow-typed version: <<STUB>>/babel-plugin-webpack-loaders_v^0.8.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-webpack-loaders'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-webpack-loaders' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-webpack-loaders/lib/memoize' {
  declare module.exports: any;
}

declare module 'babel-plugin-webpack-loaders/lib/plugin' {
  declare module.exports: any;
}

declare module 'babel-plugin-webpack-loaders/lib/runWebPackSync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-webpack-loaders/lib/memoize.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-loaders/lib/memoize'>;
}
declare module 'babel-plugin-webpack-loaders/lib/plugin.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-loaders/lib/plugin'>;
}
declare module 'babel-plugin-webpack-loaders/lib/runWebPackSync.js' {
  declare module.exports: $Exports<'babel-plugin-webpack-loaders/lib/runWebPackSync'>;
}
