// flow-typed signature: 04a5448c5e1473eb7d5e1f2c447b9a3c
// flow-typed version: <<STUB>>/babel-plugin-flow-runtime_v^0.10.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-flow-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-flow-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-flow-runtime/babel-plugin-flow-runtime' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/config/eslint' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/mocha' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/eslint-plugin-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/mobx_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/mobx-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/mocha_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/annotateVisitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/attachImport' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/collectProgramOptions' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/ConversionContext' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/convert' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/createConversionContext' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/Entity' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/findIdentifiers' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/firstPassVisitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/getTypeParameters' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/hasTypeAnnotations' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/loadFlowConfig' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/patternMatchVisitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/preTransformVisitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/symbols' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/transform' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/transformVisitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/typeAnnotationIterator' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/TypeTransformer' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/lib/util' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/annotateVisitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/attachImport' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/collectProgramOptions' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/ConversionContext' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/convert' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/createConversionContext' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/Entity' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/findIdentifiers' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/firstPassVisitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/getTypeParameters' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/hasTypeAnnotations' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/loadFlowConfig' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/patternMatchVisitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/preTransformVisitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/symbols' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/transform' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/transformVisitors' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/typeAnnotationIterator' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/src/util' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/test-polyfill' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-runtime/tools/makeFixturesJSON' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-flow-runtime/babel-plugin-flow-runtime.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/babel-plugin-flow-runtime'>;
}
declare module 'babel-plugin-flow-runtime/config/eslint.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/config/eslint'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/mocha.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/mocha'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/eslint-plugin-flow_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/eslint-plugin-flow_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/mobx_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/mobx_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/mobx-react_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/mobx-react_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/mocha_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/mocha_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'babel-plugin-flow-runtime/lib/annotateVisitors.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/annotateVisitors'>;
}
declare module 'babel-plugin-flow-runtime/lib/attachImport.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/attachImport'>;
}
declare module 'babel-plugin-flow-runtime/lib/collectProgramOptions.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/collectProgramOptions'>;
}
declare module 'babel-plugin-flow-runtime/lib/ConversionContext.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/ConversionContext'>;
}
declare module 'babel-plugin-flow-runtime/lib/convert.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/convert'>;
}
declare module 'babel-plugin-flow-runtime/lib/createConversionContext.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/createConversionContext'>;
}
declare module 'babel-plugin-flow-runtime/lib/Entity.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/Entity'>;
}
declare module 'babel-plugin-flow-runtime/lib/findIdentifiers.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/findIdentifiers'>;
}
declare module 'babel-plugin-flow-runtime/lib/firstPassVisitors.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/firstPassVisitors'>;
}
declare module 'babel-plugin-flow-runtime/lib/getTypeParameters.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/getTypeParameters'>;
}
declare module 'babel-plugin-flow-runtime/lib/hasTypeAnnotations.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/hasTypeAnnotations'>;
}
declare module 'babel-plugin-flow-runtime/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/index'>;
}
declare module 'babel-plugin-flow-runtime/lib/loadFlowConfig.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/loadFlowConfig'>;
}
declare module 'babel-plugin-flow-runtime/lib/patternMatchVisitors.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/patternMatchVisitors'>;
}
declare module 'babel-plugin-flow-runtime/lib/preTransformVisitors.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/preTransformVisitors'>;
}
declare module 'babel-plugin-flow-runtime/lib/symbols.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/symbols'>;
}
declare module 'babel-plugin-flow-runtime/lib/transform.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/transform'>;
}
declare module 'babel-plugin-flow-runtime/lib/transformVisitors.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/transformVisitors'>;
}
declare module 'babel-plugin-flow-runtime/lib/typeAnnotationIterator.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/typeAnnotationIterator'>;
}
declare module 'babel-plugin-flow-runtime/lib/TypeTransformer.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/TypeTransformer'>;
}
declare module 'babel-plugin-flow-runtime/lib/util.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/lib/util'>;
}
declare module 'babel-plugin-flow-runtime/src/annotateVisitors.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/annotateVisitors'>;
}
declare module 'babel-plugin-flow-runtime/src/attachImport.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/attachImport'>;
}
declare module 'babel-plugin-flow-runtime/src/collectProgramOptions.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/collectProgramOptions'>;
}
declare module 'babel-plugin-flow-runtime/src/ConversionContext.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/ConversionContext'>;
}
declare module 'babel-plugin-flow-runtime/src/convert.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/convert'>;
}
declare module 'babel-plugin-flow-runtime/src/createConversionContext.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/createConversionContext'>;
}
declare module 'babel-plugin-flow-runtime/src/Entity.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/Entity'>;
}
declare module 'babel-plugin-flow-runtime/src/findIdentifiers.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/findIdentifiers'>;
}
declare module 'babel-plugin-flow-runtime/src/firstPassVisitors.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/firstPassVisitors'>;
}
declare module 'babel-plugin-flow-runtime/src/getTypeParameters.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/getTypeParameters'>;
}
declare module 'babel-plugin-flow-runtime/src/hasTypeAnnotations.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/hasTypeAnnotations'>;
}
declare module 'babel-plugin-flow-runtime/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/index'>;
}
declare module 'babel-plugin-flow-runtime/src/loadFlowConfig.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/loadFlowConfig'>;
}
declare module 'babel-plugin-flow-runtime/src/patternMatchVisitors.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/patternMatchVisitors'>;
}
declare module 'babel-plugin-flow-runtime/src/preTransformVisitors.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/preTransformVisitors'>;
}
declare module 'babel-plugin-flow-runtime/src/symbols.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/symbols'>;
}
declare module 'babel-plugin-flow-runtime/src/transform.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/transform'>;
}
declare module 'babel-plugin-flow-runtime/src/transformVisitors.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/transformVisitors'>;
}
declare module 'babel-plugin-flow-runtime/src/typeAnnotationIterator.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/typeAnnotationIterator'>;
}
declare module 'babel-plugin-flow-runtime/src/util.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/src/util'>;
}
declare module 'babel-plugin-flow-runtime/test-polyfill.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/test-polyfill'>;
}
declare module 'babel-plugin-flow-runtime/tools/makeFixturesJSON.js' {
  declare module.exports: $Exports<'babel-plugin-flow-runtime/tools/makeFixturesJSON'>;
}
