// flow-typed signature: a270dd80e23736170a4f38af724d15a6
// flow-typed version: <<STUB>>/babili-webpack-plugin_v^0.0.7/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babili-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babili-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babili-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'babili-webpack-plugin/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babili-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'babili-webpack-plugin/lib/index'>;
}
declare module 'babili-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'babili-webpack-plugin/src/index'>;
}
