// flow-typed signature: dd1fcd3db4d540c9bc3edfee683480a3
// flow-typed version: <<STUB>>/concurrently_v^3.4.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'concurrently'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'concurrently' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'concurrently/src/main' {
  declare module.exports: any;
}

declare module 'concurrently/tst' {
  declare module.exports: any;
}

// Filename aliases
declare module 'concurrently/src/main.js' {
  declare module.exports: $Exports<'concurrently/src/main'>;
}
declare module 'concurrently/tst.js' {
  declare module.exports: $Exports<'concurrently/tst'>;
}
