// flow-typed signature: 7c3e1347b297a26c04d3636782602010
// flow-typed version: <<STUB>>/cross-spawn_v^5.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-spawn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-spawn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cross-spawn/lib/enoent' {
  declare module.exports: any;
}

declare module 'cross-spawn/lib/parse' {
  declare module.exports: any;
}

declare module 'cross-spawn/lib/util/escapeArgument' {
  declare module.exports: any;
}

declare module 'cross-spawn/lib/util/escapeCommand' {
  declare module.exports: any;
}

declare module 'cross-spawn/lib/util/hasEmptyArgumentBug' {
  declare module.exports: any;
}

declare module 'cross-spawn/lib/util/readShebang' {
  declare module.exports: any;
}

declare module 'cross-spawn/lib/util/resolveCommand' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cross-spawn/index' {
  declare module.exports: $Exports<'cross-spawn'>;
}
declare module 'cross-spawn/index.js' {
  declare module.exports: $Exports<'cross-spawn'>;
}
declare module 'cross-spawn/lib/enoent.js' {
  declare module.exports: $Exports<'cross-spawn/lib/enoent'>;
}
declare module 'cross-spawn/lib/parse.js' {
  declare module.exports: $Exports<'cross-spawn/lib/parse'>;
}
declare module 'cross-spawn/lib/util/escapeArgument.js' {
  declare module.exports: $Exports<'cross-spawn/lib/util/escapeArgument'>;
}
declare module 'cross-spawn/lib/util/escapeCommand.js' {
  declare module.exports: $Exports<'cross-spawn/lib/util/escapeCommand'>;
}
declare module 'cross-spawn/lib/util/hasEmptyArgumentBug.js' {
  declare module.exports: $Exports<'cross-spawn/lib/util/hasEmptyArgumentBug'>;
}
declare module 'cross-spawn/lib/util/readShebang.js' {
  declare module.exports: $Exports<'cross-spawn/lib/util/readShebang'>;
}
declare module 'cross-spawn/lib/util/resolveCommand.js' {
  declare module.exports: $Exports<'cross-spawn/lib/util/resolveCommand'>;
}
