// flow-typed signature: 18e8046e36bf12c9e3e23ea4ac659e83
// flow-typed version: <<STUB>>/devtron_v^1.4.0/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'devtron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'devtron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'devtron/api' {
  declare module.exports: any;
}

declare module 'devtron/out/browser-globals' {
  declare module.exports: any;
}

declare module 'devtron/out/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'devtron/api.js' {
  declare module.exports: $Exports<'devtron/api'>;
}
declare module 'devtron/out/browser-globals.js' {
  declare module.exports: $Exports<'devtron/out/browser-globals'>;
}
declare module 'devtron/out/index.js' {
  declare module.exports: $Exports<'devtron/out/index'>;
}
