// flow-typed signature: 7b45d807bb40517e0fb3bd6710a792b6
// flow-typed version: <<STUB>>/electron-debug_v^1.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-debug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-debug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-debug/index' {
  declare module.exports: $Exports<'electron-debug'>;
}
declare module 'electron-debug/index.js' {
  declare module.exports: $Exports<'electron-debug'>;
}
