// flow-typed signature: e57898534739eede33525e6dedd9273c
// flow-typed version: <<STUB>>/electron-rebuild_v^1.3.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-rebuild'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-rebuild' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-rebuild/lib/cli' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/electron-locater' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/main' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/node-pre-gyp-fix' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/promisify' {
  declare module.exports: any;
}

declare module 'electron-rebuild/lib/spawn' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/cli' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/electron-locater' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/main' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/node-pre-gyp-fix' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/promisify' {
  declare module.exports: any;
}

declare module 'electron-rebuild/src/spawn' {
  declare module.exports: any;
}

declare module 'electron-rebuild/test/electron-locater' {
  declare module.exports: any;
}

declare module 'electron-rebuild/test/main' {
  declare module.exports: any;
}

declare module 'electron-rebuild/test/promisify' {
  declare module.exports: any;
}

declare module 'electron-rebuild/test/spawn' {
  declare module.exports: any;
}

declare module 'electron-rebuild/test/support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-rebuild/lib/cli.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/cli'>;
}
declare module 'electron-rebuild/lib/electron-locater.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/electron-locater'>;
}
declare module 'electron-rebuild/lib/main.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/main'>;
}
declare module 'electron-rebuild/lib/node-pre-gyp-fix.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/node-pre-gyp-fix'>;
}
declare module 'electron-rebuild/lib/promisify.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/promisify'>;
}
declare module 'electron-rebuild/lib/spawn.js' {
  declare module.exports: $Exports<'electron-rebuild/lib/spawn'>;
}
declare module 'electron-rebuild/src/cli.js' {
  declare module.exports: $Exports<'electron-rebuild/src/cli'>;
}
declare module 'electron-rebuild/src/electron-locater.js' {
  declare module.exports: $Exports<'electron-rebuild/src/electron-locater'>;
}
declare module 'electron-rebuild/src/main.js' {
  declare module.exports: $Exports<'electron-rebuild/src/main'>;
}
declare module 'electron-rebuild/src/node-pre-gyp-fix.js' {
  declare module.exports: $Exports<'electron-rebuild/src/node-pre-gyp-fix'>;
}
declare module 'electron-rebuild/src/promisify.js' {
  declare module.exports: $Exports<'electron-rebuild/src/promisify'>;
}
declare module 'electron-rebuild/src/spawn.js' {
  declare module.exports: $Exports<'electron-rebuild/src/spawn'>;
}
declare module 'electron-rebuild/test/electron-locater.js' {
  declare module.exports: $Exports<'electron-rebuild/test/electron-locater'>;
}
declare module 'electron-rebuild/test/main.js' {
  declare module.exports: $Exports<'electron-rebuild/test/main'>;
}
declare module 'electron-rebuild/test/promisify.js' {
  declare module.exports: $Exports<'electron-rebuild/test/promisify'>;
}
declare module 'electron-rebuild/test/spawn.js' {
  declare module.exports: $Exports<'electron-rebuild/test/spawn'>;
}
declare module 'electron-rebuild/test/support.js' {
  declare module.exports: $Exports<'electron-rebuild/test/support'>;
}
