// flow-typed signature: 61d1f39c614c45c5ea77e53f52070884
// flow-typed version: <<STUB>>/eslint-plugin-promise_v^2.0.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-promise/rules/always-catch' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/always-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/catch-or-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/no-native' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/param-names' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/test/always-catch.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/test/always-return.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/test/catch-or-return.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/test/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/test/no-native' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/test/param-names.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-promise/index' {
  declare module.exports: $Exports<'eslint-plugin-promise'>;
}
declare module 'eslint-plugin-promise/index.js' {
  declare module.exports: $Exports<'eslint-plugin-promise'>;
}
declare module 'eslint-plugin-promise/rules/always-catch.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/always-catch'>;
}
declare module 'eslint-plugin-promise/rules/always-return.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/always-return'>;
}
declare module 'eslint-plugin-promise/rules/catch-or-return.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/catch-or-return'>;
}
declare module 'eslint-plugin-promise/rules/no-native.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/no-native'>;
}
declare module 'eslint-plugin-promise/rules/param-names.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/param-names'>;
}
declare module 'eslint-plugin-promise/test/always-catch.test.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/test/always-catch.test'>;
}
declare module 'eslint-plugin-promise/test/always-return.test.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/test/always-return.test'>;
}
declare module 'eslint-plugin-promise/test/catch-or-return.test.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/test/catch-or-return.test'>;
}
declare module 'eslint-plugin-promise/test/index.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/test/index'>;
}
declare module 'eslint-plugin-promise/test/no-native.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/test/no-native'>;
}
declare module 'eslint-plugin-promise/test/param-names.test.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/test/param-names.test'>;
}
