// flow-typed signature: d7cd9caf9ef5a308516be587b8d5c9d0
// flow-typed version: <<STUB>>/eslint-formatter-pretty_v^1.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-formatter-pretty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-formatter-pretty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-formatter-pretty/index' {
  declare module.exports: $Exports<'eslint-formatter-pretty'>;
}
declare module 'eslint-formatter-pretty/index.js' {
  declare module.exports: $Exports<'eslint-formatter-pretty'>;
}
