// flow-typed signature: 6ec63d6d2a89213d7b56630d6cd87b4b
// flow-typed version: <<STUB>>/eslint-plugin-compat_v^0.0.5/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-compat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-compat/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/Lint' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/providers/CanIUseProvider' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/providers/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/providers/KangaxProvider' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/rules/compat' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/src/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/src/Lint' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/src/providers/CanIUseProvider' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/src/providers/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/src/providers/KangaxProvider' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/src/rules/compat' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/test/caniuse/e2e.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-compat/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/index'>;
}
declare module 'eslint-plugin-compat/lib/Lint.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/Lint'>;
}
declare module 'eslint-plugin-compat/lib/providers/CanIUseProvider.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/providers/CanIUseProvider'>;
}
declare module 'eslint-plugin-compat/lib/providers/index.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/providers/index'>;
}
declare module 'eslint-plugin-compat/lib/providers/KangaxProvider.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/providers/KangaxProvider'>;
}
declare module 'eslint-plugin-compat/lib/rules/compat.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/rules/compat'>;
}
declare module 'eslint-plugin-compat/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/src/index'>;
}
declare module 'eslint-plugin-compat/src/Lint.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/src/Lint'>;
}
declare module 'eslint-plugin-compat/src/providers/CanIUseProvider.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/src/providers/CanIUseProvider'>;
}
declare module 'eslint-plugin-compat/src/providers/index.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/src/providers/index'>;
}
declare module 'eslint-plugin-compat/src/providers/KangaxProvider.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/src/providers/KangaxProvider'>;
}
declare module 'eslint-plugin-compat/src/rules/compat.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/src/rules/compat'>;
}
declare module 'eslint-plugin-compat/test/caniuse/e2e.spec.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/test/caniuse/e2e.spec'>;
}
