// flow-typed signature: f3d4f226f953b90de2f8e451c3ce619c
// flow-typed version: <<STUB>>/eslint-plugin-promise_v^3.4.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-promise/rules/always-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/avoid-new' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/catch-or-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/lib/has-promise-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/lib/is-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/lib/is-inside-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/lib/is-inside-promise' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/lib/is-named-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/lib/is-promise' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/no-callback-in-promise' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/no-native' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/no-nesting' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/no-promise-in-callback' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/no-return-wrap' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/param-names' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/prefer-await-to-callbacks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promise/rules/prefer-await-to-then' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-promise/index' {
  declare module.exports: $Exports<'eslint-plugin-promise'>;
}
declare module 'eslint-plugin-promise/index.js' {
  declare module.exports: $Exports<'eslint-plugin-promise'>;
}
declare module 'eslint-plugin-promise/rules/always-return.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/always-return'>;
}
declare module 'eslint-plugin-promise/rules/avoid-new.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/avoid-new'>;
}
declare module 'eslint-plugin-promise/rules/catch-or-return.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/catch-or-return'>;
}
declare module 'eslint-plugin-promise/rules/lib/has-promise-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/lib/has-promise-callback'>;
}
declare module 'eslint-plugin-promise/rules/lib/is-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/lib/is-callback'>;
}
declare module 'eslint-plugin-promise/rules/lib/is-inside-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/lib/is-inside-callback'>;
}
declare module 'eslint-plugin-promise/rules/lib/is-inside-promise.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/lib/is-inside-promise'>;
}
declare module 'eslint-plugin-promise/rules/lib/is-named-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/lib/is-named-callback'>;
}
declare module 'eslint-plugin-promise/rules/lib/is-promise.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/lib/is-promise'>;
}
declare module 'eslint-plugin-promise/rules/no-callback-in-promise.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/no-callback-in-promise'>;
}
declare module 'eslint-plugin-promise/rules/no-native.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/no-native'>;
}
declare module 'eslint-plugin-promise/rules/no-nesting.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/no-nesting'>;
}
declare module 'eslint-plugin-promise/rules/no-promise-in-callback.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/no-promise-in-callback'>;
}
declare module 'eslint-plugin-promise/rules/no-return-wrap.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/no-return-wrap'>;
}
declare module 'eslint-plugin-promise/rules/param-names.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/param-names'>;
}
declare module 'eslint-plugin-promise/rules/prefer-await-to-callbacks.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/prefer-await-to-callbacks'>;
}
declare module 'eslint-plugin-promise/rules/prefer-await-to-then.js' {
  declare module.exports: $Exports<'eslint-plugin-promise/rules/prefer-await-to-then'>;
}
