// flow-typed signature: 1a93f8f36cbe66bf0ca703d9ed7c2e94
// flow-typed version: <<STUB>>/fbjs-scripts_v^0.7.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fbjs-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fbjs-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fbjs-scripts/babel/default-options' {
  declare module.exports: any;
}

declare module 'fbjs-scripts/gulp/check-dependencies' {
  declare module.exports: any;
}

declare module 'fbjs-scripts/gulp/module-map' {
  declare module.exports: any;
}

declare module 'fbjs-scripts/gulp/shared/provides-module' {
  declare module.exports: any;
}

declare module 'fbjs-scripts/gulp/strip-provides-module' {
  declare module.exports: any;
}

declare module 'fbjs-scripts/jest/createCacheKeyFunction' {
  declare module.exports: any;
}

declare module 'fbjs-scripts/jest/environment' {
  declare module.exports: any;
}

declare module 'fbjs-scripts/jest/preprocessor' {
  declare module.exports: any;
}

declare module 'fbjs-scripts/node/check-dev-engines' {
  declare module.exports: any;
}

declare module 'fbjs-scripts/node/check-lib-requires' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fbjs-scripts/babel/default-options.js' {
  declare module.exports: $Exports<'fbjs-scripts/babel/default-options'>;
}
declare module 'fbjs-scripts/gulp/check-dependencies.js' {
  declare module.exports: $Exports<'fbjs-scripts/gulp/check-dependencies'>;
}
declare module 'fbjs-scripts/gulp/module-map.js' {
  declare module.exports: $Exports<'fbjs-scripts/gulp/module-map'>;
}
declare module 'fbjs-scripts/gulp/shared/provides-module.js' {
  declare module.exports: $Exports<'fbjs-scripts/gulp/shared/provides-module'>;
}
declare module 'fbjs-scripts/gulp/strip-provides-module.js' {
  declare module.exports: $Exports<'fbjs-scripts/gulp/strip-provides-module'>;
}
declare module 'fbjs-scripts/jest/createCacheKeyFunction.js' {
  declare module.exports: $Exports<'fbjs-scripts/jest/createCacheKeyFunction'>;
}
declare module 'fbjs-scripts/jest/environment.js' {
  declare module.exports: $Exports<'fbjs-scripts/jest/environment'>;
}
declare module 'fbjs-scripts/jest/preprocessor.js' {
  declare module.exports: $Exports<'fbjs-scripts/jest/preprocessor'>;
}
declare module 'fbjs-scripts/node/check-dev-engines.js' {
  declare module.exports: $Exports<'fbjs-scripts/node/check-dev-engines'>;
}
declare module 'fbjs-scripts/node/check-lib-requires.js' {
  declare module.exports: $Exports<'fbjs-scripts/node/check-lib-requires'>;
}
