// flow-typed signature: f74d42a8c88cb48ab661eaa0f87753c5
// flow-typed version: <<STUB>>/file-loader_v^0.9.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'file-loader/index' {
  declare module.exports: $Exports<'file-loader'>;
}
declare module 'file-loader/index.js' {
  declare module.exports: $Exports<'file-loader'>;
}
