// flow-typed signature: 0cc9623f5546124eb3dc843f1d415c72
// flow-typed version: <<STUB>>/jest-cli_v^17.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-cli/bin/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/args' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/getJest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/index' {
  declare module.exports: any;
}

declare module 'jest-cli/build/generateEmptyCoverage' {
  declare module.exports: any;
}

declare module 'jest-cli/build/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/BufferedConsole' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/formatTestResults' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/promisify' {
  declare module.exports: any;
}

declare module 'jest-cli/build/preRunMessage' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/BaseReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/CoverageReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/DefaultReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/getConsoleOutput' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/getResultHeader' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/NotifyReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/Status' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/SummaryReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/utils' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/VerboseReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/runTest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/SearchSource' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestRunner' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestWatcher' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-cli/bin/jest.js' {
  declare module.exports: $Exports<'jest-cli/bin/jest'>;
}
declare module 'jest-cli/build/cli/args.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/args'>;
}
declare module 'jest-cli/build/cli/getJest.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/getJest'>;
}
declare module 'jest-cli/build/cli/index.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/index'>;
}
declare module 'jest-cli/build/generateEmptyCoverage.js' {
  declare module.exports: $Exports<'jest-cli/build/generateEmptyCoverage'>;
}
declare module 'jest-cli/build/jest.js' {
  declare module.exports: $Exports<'jest-cli/build/jest'>;
}
declare module 'jest-cli/build/lib/BufferedConsole.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/BufferedConsole'>;
}
declare module 'jest-cli/build/lib/formatTestResults.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/formatTestResults'>;
}
declare module 'jest-cli/build/lib/promisify.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/promisify'>;
}
declare module 'jest-cli/build/preRunMessage.js' {
  declare module.exports: $Exports<'jest-cli/build/preRunMessage'>;
}
declare module 'jest-cli/build/reporters/BaseReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/BaseReporter'>;
}
declare module 'jest-cli/build/reporters/CoverageReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/CoverageReporter'>;
}
declare module 'jest-cli/build/reporters/DefaultReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/DefaultReporter'>;
}
declare module 'jest-cli/build/reporters/getConsoleOutput.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/getConsoleOutput'>;
}
declare module 'jest-cli/build/reporters/getResultHeader.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/getResultHeader'>;
}
declare module 'jest-cli/build/reporters/NotifyReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/NotifyReporter'>;
}
declare module 'jest-cli/build/reporters/Status.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/Status'>;
}
declare module 'jest-cli/build/reporters/SummaryReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/SummaryReporter'>;
}
declare module 'jest-cli/build/reporters/utils.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/utils'>;
}
declare module 'jest-cli/build/reporters/VerboseReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/VerboseReporter'>;
}
declare module 'jest-cli/build/runTest.js' {
  declare module.exports: $Exports<'jest-cli/build/runTest'>;
}
declare module 'jest-cli/build/SearchSource.js' {
  declare module.exports: $Exports<'jest-cli/build/SearchSource'>;
}
declare module 'jest-cli/build/TestRunner.js' {
  declare module.exports: $Exports<'jest-cli/build/TestRunner'>;
}
declare module 'jest-cli/build/TestWatcher.js' {
  declare module.exports: $Exports<'jest-cli/build/TestWatcher'>;
}
declare module 'jest-cli/build/TestWorker.js' {
  declare module.exports: $Exports<'jest-cli/build/TestWorker'>;
}
