// flow-typed signature: efe1abf94d69019d0f511984d7dc070b
// flow-typed version: <<STUB>>/node-sass_v^4.5.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-sass/lib/binding' {
  declare module.exports: any;
}

declare module 'node-sass/lib/errors' {
  declare module.exports: any;
}

declare module 'node-sass/lib/extensions' {
  declare module.exports: any;
}

declare module 'node-sass/lib/index' {
  declare module.exports: any;
}

declare module 'node-sass/lib/render' {
  declare module.exports: any;
}

declare module 'node-sass/scripts/build' {
  declare module.exports: any;
}

declare module 'node-sass/scripts/coverage' {
  declare module.exports: any;
}

declare module 'node-sass/scripts/install' {
  declare module.exports: any;
}

declare module 'node-sass/scripts/prepublish' {
  declare module.exports: any;
}

declare module 'node-sass/scripts/util/downloadoptions' {
  declare module.exports: any;
}

declare module 'node-sass/scripts/util/proxy' {
  declare module.exports: any;
}

declare module 'node-sass/scripts/util/useragent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-sass/lib/binding.js' {
  declare module.exports: $Exports<'node-sass/lib/binding'>;
}
declare module 'node-sass/lib/errors.js' {
  declare module.exports: $Exports<'node-sass/lib/errors'>;
}
declare module 'node-sass/lib/extensions.js' {
  declare module.exports: $Exports<'node-sass/lib/extensions'>;
}
declare module 'node-sass/lib/index.js' {
  declare module.exports: $Exports<'node-sass/lib/index'>;
}
declare module 'node-sass/lib/render.js' {
  declare module.exports: $Exports<'node-sass/lib/render'>;
}
declare module 'node-sass/scripts/build.js' {
  declare module.exports: $Exports<'node-sass/scripts/build'>;
}
declare module 'node-sass/scripts/coverage.js' {
  declare module.exports: $Exports<'node-sass/scripts/coverage'>;
}
declare module 'node-sass/scripts/install.js' {
  declare module.exports: $Exports<'node-sass/scripts/install'>;
}
declare module 'node-sass/scripts/prepublish.js' {
  declare module.exports: $Exports<'node-sass/scripts/prepublish'>;
}
declare module 'node-sass/scripts/util/downloadoptions.js' {
  declare module.exports: $Exports<'node-sass/scripts/util/downloadoptions'>;
}
declare module 'node-sass/scripts/util/proxy.js' {
  declare module.exports: $Exports<'node-sass/scripts/util/proxy'>;
}
declare module 'node-sass/scripts/util/useragent.js' {
  declare module.exports: $Exports<'node-sass/scripts/util/useragent'>;
}
