// flow-typed signature: 56925c83c2319e628d6f61784457ffd3
// flow-typed version: <<STUB>>/postcss_v^5.2.5/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss/lib/at-rule' {
  declare module.exports: any;
}

declare module 'postcss/lib/comment' {
  declare module.exports: any;
}

declare module 'postcss/lib/container' {
  declare module.exports: any;
}

declare module 'postcss/lib/css-syntax-error' {
  declare module.exports: any;
}

declare module 'postcss/lib/declaration' {
  declare module.exports: any;
}

declare module 'postcss/lib/input' {
  declare module.exports: any;
}

declare module 'postcss/lib/lazy-result' {
  declare module.exports: any;
}

declare module 'postcss/lib/list' {
  declare module.exports: any;
}

declare module 'postcss/lib/map-generator' {
  declare module.exports: any;
}

declare module 'postcss/lib/node' {
  declare module.exports: any;
}

declare module 'postcss/lib/parse' {
  declare module.exports: any;
}

declare module 'postcss/lib/parser' {
  declare module.exports: any;
}

declare module 'postcss/lib/postcss' {
  declare module.exports: any;
}

declare module 'postcss/lib/previous-map' {
  declare module.exports: any;
}

declare module 'postcss/lib/processor' {
  declare module.exports: any;
}

declare module 'postcss/lib/result' {
  declare module.exports: any;
}

declare module 'postcss/lib/root' {
  declare module.exports: any;
}

declare module 'postcss/lib/rule' {
  declare module.exports: any;
}

declare module 'postcss/lib/stringifier' {
  declare module.exports: any;
}

declare module 'postcss/lib/stringify' {
  declare module.exports: any;
}

declare module 'postcss/lib/terminal-highlight' {
  declare module.exports: any;
}

declare module 'postcss/lib/tokenize' {
  declare module.exports: any;
}

declare module 'postcss/lib/vendor' {
  declare module.exports: any;
}

declare module 'postcss/lib/warn-once' {
  declare module.exports: any;
}

declare module 'postcss/lib/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss/lib/at-rule.js' {
  declare module.exports: $Exports<'postcss/lib/at-rule'>;
}
declare module 'postcss/lib/comment.js' {
  declare module.exports: $Exports<'postcss/lib/comment'>;
}
declare module 'postcss/lib/container.js' {
  declare module.exports: $Exports<'postcss/lib/container'>;
}
declare module 'postcss/lib/css-syntax-error.js' {
  declare module.exports: $Exports<'postcss/lib/css-syntax-error'>;
}
declare module 'postcss/lib/declaration.js' {
  declare module.exports: $Exports<'postcss/lib/declaration'>;
}
declare module 'postcss/lib/input.js' {
  declare module.exports: $Exports<'postcss/lib/input'>;
}
declare module 'postcss/lib/lazy-result.js' {
  declare module.exports: $Exports<'postcss/lib/lazy-result'>;
}
declare module 'postcss/lib/list.js' {
  declare module.exports: $Exports<'postcss/lib/list'>;
}
declare module 'postcss/lib/map-generator.js' {
  declare module.exports: $Exports<'postcss/lib/map-generator'>;
}
declare module 'postcss/lib/node.js' {
  declare module.exports: $Exports<'postcss/lib/node'>;
}
declare module 'postcss/lib/parse.js' {
  declare module.exports: $Exports<'postcss/lib/parse'>;
}
declare module 'postcss/lib/parser.js' {
  declare module.exports: $Exports<'postcss/lib/parser'>;
}
declare module 'postcss/lib/postcss.js' {
  declare module.exports: $Exports<'postcss/lib/postcss'>;
}
declare module 'postcss/lib/previous-map.js' {
  declare module.exports: $Exports<'postcss/lib/previous-map'>;
}
declare module 'postcss/lib/processor.js' {
  declare module.exports: $Exports<'postcss/lib/processor'>;
}
declare module 'postcss/lib/result.js' {
  declare module.exports: $Exports<'postcss/lib/result'>;
}
declare module 'postcss/lib/root.js' {
  declare module.exports: $Exports<'postcss/lib/root'>;
}
declare module 'postcss/lib/rule.js' {
  declare module.exports: $Exports<'postcss/lib/rule'>;
}
declare module 'postcss/lib/stringifier.js' {
  declare module.exports: $Exports<'postcss/lib/stringifier'>;
}
declare module 'postcss/lib/stringify.js' {
  declare module.exports: $Exports<'postcss/lib/stringify'>;
}
declare module 'postcss/lib/terminal-highlight.js' {
  declare module.exports: $Exports<'postcss/lib/terminal-highlight'>;
}
declare module 'postcss/lib/tokenize.js' {
  declare module.exports: $Exports<'postcss/lib/tokenize'>;
}
declare module 'postcss/lib/vendor.js' {
  declare module.exports: $Exports<'postcss/lib/vendor'>;
}
declare module 'postcss/lib/warn-once.js' {
  declare module.exports: $Exports<'postcss/lib/warn-once'>;
}
declare module 'postcss/lib/warning.js' {
  declare module.exports: $Exports<'postcss/lib/warning'>;
}
