// flow-typed signature: 4abfa38151a09b93891d640ec27c7d4c
// flow-typed version: <<STUB>>/react-router_v^3.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/es/applyRouterMiddleware' {
  declare module.exports: any;
}

declare module 'react-router/es/AsyncUtils' {
  declare module.exports: any;
}

declare module 'react-router/es/browserHistory' {
  declare module.exports: any;
}

declare module 'react-router/es/computeChangedRoutes' {
  declare module.exports: any;
}

declare module 'react-router/es/ContextUtils' {
  declare module.exports: any;
}

declare module 'react-router/es/createMemoryHistory' {
  declare module.exports: any;
}

declare module 'react-router/es/createRouterHistory' {
  declare module.exports: any;
}

declare module 'react-router/es/createTransitionManager' {
  declare module.exports: any;
}

declare module 'react-router/es/getComponents' {
  declare module.exports: any;
}

declare module 'react-router/es/getRouteParams' {
  declare module.exports: any;
}

declare module 'react-router/es/hashHistory' {
  declare module.exports: any;
}

declare module 'react-router/es/index' {
  declare module.exports: any;
}

declare module 'react-router/es/IndexLink' {
  declare module.exports: any;
}

declare module 'react-router/es/IndexRedirect' {
  declare module.exports: any;
}

declare module 'react-router/es/IndexRoute' {
  declare module.exports: any;
}

declare module 'react-router/es/InternalPropTypes' {
  declare module.exports: any;
}

declare module 'react-router/es/isActive' {
  declare module.exports: any;
}

declare module 'react-router/es/Link' {
  declare module.exports: any;
}

declare module 'react-router/es/match' {
  declare module.exports: any;
}

declare module 'react-router/es/matchRoutes' {
  declare module.exports: any;
}

declare module 'react-router/es/PatternUtils' {
  declare module.exports: any;
}

declare module 'react-router/es/PromiseUtils' {
  declare module.exports: any;
}

declare module 'react-router/es/PropTypes' {
  declare module.exports: any;
}

declare module 'react-router/es/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/es/Route' {
  declare module.exports: any;
}

declare module 'react-router/es/Router' {
  declare module.exports: any;
}

declare module 'react-router/es/RouterContext' {
  declare module.exports: any;
}

declare module 'react-router/es/RouterUtils' {
  declare module.exports: any;
}

declare module 'react-router/es/routerWarning' {
  declare module.exports: any;
}

declare module 'react-router/es/RouteUtils' {
  declare module.exports: any;
}

declare module 'react-router/es/TransitionUtils' {
  declare module.exports: any;
}

declare module 'react-router/es/useRouterHistory' {
  declare module.exports: any;
}

declare module 'react-router/es/withRouter' {
  declare module.exports: any;
}

declare module 'react-router/lib/applyRouterMiddleware' {
  declare module.exports: any;
}

declare module 'react-router/lib/AsyncUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/browserHistory' {
  declare module.exports: any;
}

declare module 'react-router/lib/computeChangedRoutes' {
  declare module.exports: any;
}

declare module 'react-router/lib/ContextUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/createMemoryHistory' {
  declare module.exports: any;
}

declare module 'react-router/lib/createRouterHistory' {
  declare module.exports: any;
}

declare module 'react-router/lib/createTransitionManager' {
  declare module.exports: any;
}

declare module 'react-router/lib/getComponents' {
  declare module.exports: any;
}

declare module 'react-router/lib/getRouteParams' {
  declare module.exports: any;
}

declare module 'react-router/lib/hashHistory' {
  declare module.exports: any;
}

declare module 'react-router/lib/index' {
  declare module.exports: any;
}

declare module 'react-router/lib/IndexLink' {
  declare module.exports: any;
}

declare module 'react-router/lib/IndexRedirect' {
  declare module.exports: any;
}

declare module 'react-router/lib/IndexRoute' {
  declare module.exports: any;
}

declare module 'react-router/lib/InternalPropTypes' {
  declare module.exports: any;
}

declare module 'react-router/lib/isActive' {
  declare module.exports: any;
}

declare module 'react-router/lib/Link' {
  declare module.exports: any;
}

declare module 'react-router/lib/match' {
  declare module.exports: any;
}

declare module 'react-router/lib/matchRoutes' {
  declare module.exports: any;
}

declare module 'react-router/lib/PatternUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/PromiseUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/PropTypes' {
  declare module.exports: any;
}

declare module 'react-router/lib/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/lib/Route' {
  declare module.exports: any;
}

declare module 'react-router/lib/Router' {
  declare module.exports: any;
}

declare module 'react-router/lib/RouterContext' {
  declare module.exports: any;
}

declare module 'react-router/lib/RouterUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/routerWarning' {
  declare module.exports: any;
}

declare module 'react-router/lib/RouteUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/TransitionUtils' {
  declare module.exports: any;
}

declare module 'react-router/lib/useRouterHistory' {
  declare module.exports: any;
}

declare module 'react-router/lib/withRouter' {
  declare module.exports: any;
}

declare module 'react-router/umd/ReactRouter' {
  declare module.exports: any;
}

declare module 'react-router/umd/ReactRouter.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/es/applyRouterMiddleware.js' {
  declare module.exports: $Exports<'react-router/es/applyRouterMiddleware'>;
}
declare module 'react-router/es/AsyncUtils.js' {
  declare module.exports: $Exports<'react-router/es/AsyncUtils'>;
}
declare module 'react-router/es/browserHistory.js' {
  declare module.exports: $Exports<'react-router/es/browserHistory'>;
}
declare module 'react-router/es/computeChangedRoutes.js' {
  declare module.exports: $Exports<'react-router/es/computeChangedRoutes'>;
}
declare module 'react-router/es/ContextUtils.js' {
  declare module.exports: $Exports<'react-router/es/ContextUtils'>;
}
declare module 'react-router/es/createMemoryHistory.js' {
  declare module.exports: $Exports<'react-router/es/createMemoryHistory'>;
}
declare module 'react-router/es/createRouterHistory.js' {
  declare module.exports: $Exports<'react-router/es/createRouterHistory'>;
}
declare module 'react-router/es/createTransitionManager.js' {
  declare module.exports: $Exports<'react-router/es/createTransitionManager'>;
}
declare module 'react-router/es/getComponents.js' {
  declare module.exports: $Exports<'react-router/es/getComponents'>;
}
declare module 'react-router/es/getRouteParams.js' {
  declare module.exports: $Exports<'react-router/es/getRouteParams'>;
}
declare module 'react-router/es/hashHistory.js' {
  declare module.exports: $Exports<'react-router/es/hashHistory'>;
}
declare module 'react-router/es/index.js' {
  declare module.exports: $Exports<'react-router/es/index'>;
}
declare module 'react-router/es/IndexLink.js' {
  declare module.exports: $Exports<'react-router/es/IndexLink'>;
}
declare module 'react-router/es/IndexRedirect.js' {
  declare module.exports: $Exports<'react-router/es/IndexRedirect'>;
}
declare module 'react-router/es/IndexRoute.js' {
  declare module.exports: $Exports<'react-router/es/IndexRoute'>;
}
declare module 'react-router/es/InternalPropTypes.js' {
  declare module.exports: $Exports<'react-router/es/InternalPropTypes'>;
}
declare module 'react-router/es/isActive.js' {
  declare module.exports: $Exports<'react-router/es/isActive'>;
}
declare module 'react-router/es/Link.js' {
  declare module.exports: $Exports<'react-router/es/Link'>;
}
declare module 'react-router/es/match.js' {
  declare module.exports: $Exports<'react-router/es/match'>;
}
declare module 'react-router/es/matchRoutes.js' {
  declare module.exports: $Exports<'react-router/es/matchRoutes'>;
}
declare module 'react-router/es/PatternUtils.js' {
  declare module.exports: $Exports<'react-router/es/PatternUtils'>;
}
declare module 'react-router/es/PromiseUtils.js' {
  declare module.exports: $Exports<'react-router/es/PromiseUtils'>;
}
declare module 'react-router/es/PropTypes.js' {
  declare module.exports: $Exports<'react-router/es/PropTypes'>;
}
declare module 'react-router/es/Redirect.js' {
  declare module.exports: $Exports<'react-router/es/Redirect'>;
}
declare module 'react-router/es/Route.js' {
  declare module.exports: $Exports<'react-router/es/Route'>;
}
declare module 'react-router/es/Router.js' {
  declare module.exports: $Exports<'react-router/es/Router'>;
}
declare module 'react-router/es/RouterContext.js' {
  declare module.exports: $Exports<'react-router/es/RouterContext'>;
}
declare module 'react-router/es/RouterUtils.js' {
  declare module.exports: $Exports<'react-router/es/RouterUtils'>;
}
declare module 'react-router/es/routerWarning.js' {
  declare module.exports: $Exports<'react-router/es/routerWarning'>;
}
declare module 'react-router/es/RouteUtils.js' {
  declare module.exports: $Exports<'react-router/es/RouteUtils'>;
}
declare module 'react-router/es/TransitionUtils.js' {
  declare module.exports: $Exports<'react-router/es/TransitionUtils'>;
}
declare module 'react-router/es/useRouterHistory.js' {
  declare module.exports: $Exports<'react-router/es/useRouterHistory'>;
}
declare module 'react-router/es/withRouter.js' {
  declare module.exports: $Exports<'react-router/es/withRouter'>;
}
declare module 'react-router/lib/applyRouterMiddleware.js' {
  declare module.exports: $Exports<'react-router/lib/applyRouterMiddleware'>;
}
declare module 'react-router/lib/AsyncUtils.js' {
  declare module.exports: $Exports<'react-router/lib/AsyncUtils'>;
}
declare module 'react-router/lib/browserHistory.js' {
  declare module.exports: $Exports<'react-router/lib/browserHistory'>;
}
declare module 'react-router/lib/computeChangedRoutes.js' {
  declare module.exports: $Exports<'react-router/lib/computeChangedRoutes'>;
}
declare module 'react-router/lib/ContextUtils.js' {
  declare module.exports: $Exports<'react-router/lib/ContextUtils'>;
}
declare module 'react-router/lib/createMemoryHistory.js' {
  declare module.exports: $Exports<'react-router/lib/createMemoryHistory'>;
}
declare module 'react-router/lib/createRouterHistory.js' {
  declare module.exports: $Exports<'react-router/lib/createRouterHistory'>;
}
declare module 'react-router/lib/createTransitionManager.js' {
  declare module.exports: $Exports<'react-router/lib/createTransitionManager'>;
}
declare module 'react-router/lib/getComponents.js' {
  declare module.exports: $Exports<'react-router/lib/getComponents'>;
}
declare module 'react-router/lib/getRouteParams.js' {
  declare module.exports: $Exports<'react-router/lib/getRouteParams'>;
}
declare module 'react-router/lib/hashHistory.js' {
  declare module.exports: $Exports<'react-router/lib/hashHistory'>;
}
declare module 'react-router/lib/index.js' {
  declare module.exports: $Exports<'react-router/lib/index'>;
}
declare module 'react-router/lib/IndexLink.js' {
  declare module.exports: $Exports<'react-router/lib/IndexLink'>;
}
declare module 'react-router/lib/IndexRedirect.js' {
  declare module.exports: $Exports<'react-router/lib/IndexRedirect'>;
}
declare module 'react-router/lib/IndexRoute.js' {
  declare module.exports: $Exports<'react-router/lib/IndexRoute'>;
}
declare module 'react-router/lib/InternalPropTypes.js' {
  declare module.exports: $Exports<'react-router/lib/InternalPropTypes'>;
}
declare module 'react-router/lib/isActive.js' {
  declare module.exports: $Exports<'react-router/lib/isActive'>;
}
declare module 'react-router/lib/Link.js' {
  declare module.exports: $Exports<'react-router/lib/Link'>;
}
declare module 'react-router/lib/match.js' {
  declare module.exports: $Exports<'react-router/lib/match'>;
}
declare module 'react-router/lib/matchRoutes.js' {
  declare module.exports: $Exports<'react-router/lib/matchRoutes'>;
}
declare module 'react-router/lib/PatternUtils.js' {
  declare module.exports: $Exports<'react-router/lib/PatternUtils'>;
}
declare module 'react-router/lib/PromiseUtils.js' {
  declare module.exports: $Exports<'react-router/lib/PromiseUtils'>;
}
declare module 'react-router/lib/PropTypes.js' {
  declare module.exports: $Exports<'react-router/lib/PropTypes'>;
}
declare module 'react-router/lib/Redirect.js' {
  declare module.exports: $Exports<'react-router/lib/Redirect'>;
}
declare module 'react-router/lib/Route.js' {
  declare module.exports: $Exports<'react-router/lib/Route'>;
}
declare module 'react-router/lib/Router.js' {
  declare module.exports: $Exports<'react-router/lib/Router'>;
}
declare module 'react-router/lib/RouterContext.js' {
  declare module.exports: $Exports<'react-router/lib/RouterContext'>;
}
declare module 'react-router/lib/RouterUtils.js' {
  declare module.exports: $Exports<'react-router/lib/RouterUtils'>;
}
declare module 'react-router/lib/routerWarning.js' {
  declare module.exports: $Exports<'react-router/lib/routerWarning'>;
}
declare module 'react-router/lib/RouteUtils.js' {
  declare module.exports: $Exports<'react-router/lib/RouteUtils'>;
}
declare module 'react-router/lib/TransitionUtils.js' {
  declare module.exports: $Exports<'react-router/lib/TransitionUtils'>;
}
declare module 'react-router/lib/useRouterHistory.js' {
  declare module.exports: $Exports<'react-router/lib/useRouterHistory'>;
}
declare module 'react-router/lib/withRouter.js' {
  declare module.exports: $Exports<'react-router/lib/withRouter'>;
}
declare module 'react-router/umd/ReactRouter.js' {
  declare module.exports: $Exports<'react-router/umd/ReactRouter'>;
}
declare module 'react-router/umd/ReactRouter.min.js' {
  declare module.exports: $Exports<'react-router/umd/ReactRouter.min'>;
}
