// flow-typed signature: 0154056f337d01a6931a89e29ef5432d
// flow-typed version: <<STUB>>/react-router-redux_v^4.0.7/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-redux/dist/ReactRouterRedux' {
  declare module.exports: any;
}

declare module 'react-router-redux/dist/ReactRouterRedux.min' {
  declare module.exports: any;
}

declare module 'react-router-redux/lib/actions' {
  declare module.exports: any;
}

declare module 'react-router-redux/lib/index' {
  declare module.exports: any;
}

declare module 'react-router-redux/lib/middleware' {
  declare module.exports: any;
}

declare module 'react-router-redux/lib/reducer' {
  declare module.exports: any;
}

declare module 'react-router-redux/lib/sync' {
  declare module.exports: any;
}

declare module 'react-router-redux/src/actions' {
  declare module.exports: any;
}

declare module 'react-router-redux/src/index' {
  declare module.exports: any;
}

declare module 'react-router-redux/src/middleware' {
  declare module.exports: any;
}

declare module 'react-router-redux/src/reducer' {
  declare module.exports: any;
}

declare module 'react-router-redux/src/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-redux/dist/ReactRouterRedux.js' {
  declare module.exports: $Exports<'react-router-redux/dist/ReactRouterRedux'>;
}
declare module 'react-router-redux/dist/ReactRouterRedux.min.js' {
  declare module.exports: $Exports<'react-router-redux/dist/ReactRouterRedux.min'>;
}
declare module 'react-router-redux/lib/actions.js' {
  declare module.exports: $Exports<'react-router-redux/lib/actions'>;
}
declare module 'react-router-redux/lib/index.js' {
  declare module.exports: $Exports<'react-router-redux/lib/index'>;
}
declare module 'react-router-redux/lib/middleware.js' {
  declare module.exports: $Exports<'react-router-redux/lib/middleware'>;
}
declare module 'react-router-redux/lib/reducer.js' {
  declare module.exports: $Exports<'react-router-redux/lib/reducer'>;
}
declare module 'react-router-redux/lib/sync.js' {
  declare module.exports: $Exports<'react-router-redux/lib/sync'>;
}
declare module 'react-router-redux/src/actions.js' {
  declare module.exports: $Exports<'react-router-redux/src/actions'>;
}
declare module 'react-router-redux/src/index.js' {
  declare module.exports: $Exports<'react-router-redux/src/index'>;
}
declare module 'react-router-redux/src/middleware.js' {
  declare module.exports: $Exports<'react-router-redux/src/middleware'>;
}
declare module 'react-router-redux/src/reducer.js' {
  declare module.exports: $Exports<'react-router-redux/src/reducer'>;
}
declare module 'react-router-redux/src/sync.js' {
  declare module.exports: $Exports<'react-router-redux/src/sync'>;
}
