// flow-typed signature: 5504f4b5e415ead59f2c3a62ee350d4f
// flow-typed version: <<STUB>>/react-redux_v^5.0.1/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux/dist/react-redux' {
  declare module.exports: any;
}

declare module 'react-redux/dist/react-redux.min' {
  declare module.exports: any;
}

declare module 'react-redux/es/components/connectAdvanced' {
  declare module.exports: any;
}

declare module 'react-redux/es/components/Provider' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/connect' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/mapDispatchToProps' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/mapStateToProps' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/mergeProps' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/selectorFactory' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/verifySubselectors' {
  declare module.exports: any;
}

declare module 'react-redux/es/connect/wrapMapToProps' {
  declare module.exports: any;
}

declare module 'react-redux/es/index' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/storeShape' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/Subscription' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/verifyPlainObject' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/warning' {
  declare module.exports: any;
}

declare module 'react-redux/es/utils/wrapActionCreators' {
  declare module.exports: any;
}

declare module 'react-redux/lib/components/connectAdvanced' {
  declare module.exports: any;
}

declare module 'react-redux/lib/components/Provider' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/connect' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/mapDispatchToProps' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/mapStateToProps' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/mergeProps' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/selectorFactory' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/verifySubselectors' {
  declare module.exports: any;
}

declare module 'react-redux/lib/connect/wrapMapToProps' {
  declare module.exports: any;
}

declare module 'react-redux/lib/index' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/storeShape' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/Subscription' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/verifyPlainObject' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/warning' {
  declare module.exports: any;
}

declare module 'react-redux/lib/utils/wrapActionCreators' {
  declare module.exports: any;
}

declare module 'react-redux/src/components/connectAdvanced' {
  declare module.exports: any;
}

declare module 'react-redux/src/components/Provider' {
  declare module.exports: any;
}

declare module 'react-redux/src/connect/connect' {
  declare module.exports: any;
}

declare module 'react-redux/src/connect/mapDispatchToProps' {
  declare module.exports: any;
}

declare module 'react-redux/src/connect/mapStateToProps' {
  declare module.exports: any;
}

declare module 'react-redux/src/connect/mergeProps' {
  declare module.exports: any;
}

declare module 'react-redux/src/connect/selectorFactory' {
  declare module.exports: any;
}

declare module 'react-redux/src/connect/verifySubselectors' {
  declare module.exports: any;
}

declare module 'react-redux/src/connect/wrapMapToProps' {
  declare module.exports: any;
}

declare module 'react-redux/src/index' {
  declare module.exports: any;
}

declare module 'react-redux/src/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-redux/src/utils/storeShape' {
  declare module.exports: any;
}

declare module 'react-redux/src/utils/Subscription' {
  declare module.exports: any;
}

declare module 'react-redux/src/utils/verifyPlainObject' {
  declare module.exports: any;
}

declare module 'react-redux/src/utils/warning' {
  declare module.exports: any;
}

declare module 'react-redux/src/utils/wrapActionCreators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux/dist/react-redux.js' {
  declare module.exports: $Exports<'react-redux/dist/react-redux'>;
}
declare module 'react-redux/dist/react-redux.min.js' {
  declare module.exports: $Exports<'react-redux/dist/react-redux.min'>;
}
declare module 'react-redux/es/components/connectAdvanced.js' {
  declare module.exports: $Exports<'react-redux/es/components/connectAdvanced'>;
}
declare module 'react-redux/es/components/Provider.js' {
  declare module.exports: $Exports<'react-redux/es/components/Provider'>;
}
declare module 'react-redux/es/connect/connect.js' {
  declare module.exports: $Exports<'react-redux/es/connect/connect'>;
}
declare module 'react-redux/es/connect/mapDispatchToProps.js' {
  declare module.exports: $Exports<'react-redux/es/connect/mapDispatchToProps'>;
}
declare module 'react-redux/es/connect/mapStateToProps.js' {
  declare module.exports: $Exports<'react-redux/es/connect/mapStateToProps'>;
}
declare module 'react-redux/es/connect/mergeProps.js' {
  declare module.exports: $Exports<'react-redux/es/connect/mergeProps'>;
}
declare module 'react-redux/es/connect/selectorFactory.js' {
  declare module.exports: $Exports<'react-redux/es/connect/selectorFactory'>;
}
declare module 'react-redux/es/connect/verifySubselectors.js' {
  declare module.exports: $Exports<'react-redux/es/connect/verifySubselectors'>;
}
declare module 'react-redux/es/connect/wrapMapToProps.js' {
  declare module.exports: $Exports<'react-redux/es/connect/wrapMapToProps'>;
}
declare module 'react-redux/es/index.js' {
  declare module.exports: $Exports<'react-redux/es/index'>;
}
declare module 'react-redux/es/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-redux/es/utils/shallowEqual'>;
}
declare module 'react-redux/es/utils/storeShape.js' {
  declare module.exports: $Exports<'react-redux/es/utils/storeShape'>;
}
declare module 'react-redux/es/utils/Subscription.js' {
  declare module.exports: $Exports<'react-redux/es/utils/Subscription'>;
}
declare module 'react-redux/es/utils/verifyPlainObject.js' {
  declare module.exports: $Exports<'react-redux/es/utils/verifyPlainObject'>;
}
declare module 'react-redux/es/utils/warning.js' {
  declare module.exports: $Exports<'react-redux/es/utils/warning'>;
}
declare module 'react-redux/es/utils/wrapActionCreators.js' {
  declare module.exports: $Exports<'react-redux/es/utils/wrapActionCreators'>;
}
declare module 'react-redux/lib/components/connectAdvanced.js' {
  declare module.exports: $Exports<'react-redux/lib/components/connectAdvanced'>;
}
declare module 'react-redux/lib/components/Provider.js' {
  declare module.exports: $Exports<'react-redux/lib/components/Provider'>;
}
declare module 'react-redux/lib/connect/connect.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/connect'>;
}
declare module 'react-redux/lib/connect/mapDispatchToProps.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/mapDispatchToProps'>;
}
declare module 'react-redux/lib/connect/mapStateToProps.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/mapStateToProps'>;
}
declare module 'react-redux/lib/connect/mergeProps.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/mergeProps'>;
}
declare module 'react-redux/lib/connect/selectorFactory.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/selectorFactory'>;
}
declare module 'react-redux/lib/connect/verifySubselectors.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/verifySubselectors'>;
}
declare module 'react-redux/lib/connect/wrapMapToProps.js' {
  declare module.exports: $Exports<'react-redux/lib/connect/wrapMapToProps'>;
}
declare module 'react-redux/lib/index.js' {
  declare module.exports: $Exports<'react-redux/lib/index'>;
}
declare module 'react-redux/lib/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/shallowEqual'>;
}
declare module 'react-redux/lib/utils/storeShape.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/storeShape'>;
}
declare module 'react-redux/lib/utils/Subscription.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/Subscription'>;
}
declare module 'react-redux/lib/utils/verifyPlainObject.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/verifyPlainObject'>;
}
declare module 'react-redux/lib/utils/warning.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/warning'>;
}
declare module 'react-redux/lib/utils/wrapActionCreators.js' {
  declare module.exports: $Exports<'react-redux/lib/utils/wrapActionCreators'>;
}
declare module 'react-redux/src/components/connectAdvanced.js' {
  declare module.exports: $Exports<'react-redux/src/components/connectAdvanced'>;
}
declare module 'react-redux/src/components/Provider.js' {
  declare module.exports: $Exports<'react-redux/src/components/Provider'>;
}
declare module 'react-redux/src/connect/connect.js' {
  declare module.exports: $Exports<'react-redux/src/connect/connect'>;
}
declare module 'react-redux/src/connect/mapDispatchToProps.js' {
  declare module.exports: $Exports<'react-redux/src/connect/mapDispatchToProps'>;
}
declare module 'react-redux/src/connect/mapStateToProps.js' {
  declare module.exports: $Exports<'react-redux/src/connect/mapStateToProps'>;
}
declare module 'react-redux/src/connect/mergeProps.js' {
  declare module.exports: $Exports<'react-redux/src/connect/mergeProps'>;
}
declare module 'react-redux/src/connect/selectorFactory.js' {
  declare module.exports: $Exports<'react-redux/src/connect/selectorFactory'>;
}
declare module 'react-redux/src/connect/verifySubselectors.js' {
  declare module.exports: $Exports<'react-redux/src/connect/verifySubselectors'>;
}
declare module 'react-redux/src/connect/wrapMapToProps.js' {
  declare module.exports: $Exports<'react-redux/src/connect/wrapMapToProps'>;
}
declare module 'react-redux/src/index.js' {
  declare module.exports: $Exports<'react-redux/src/index'>;
}
declare module 'react-redux/src/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-redux/src/utils/shallowEqual'>;
}
declare module 'react-redux/src/utils/storeShape.js' {
  declare module.exports: $Exports<'react-redux/src/utils/storeShape'>;
}
declare module 'react-redux/src/utils/Subscription.js' {
  declare module.exports: $Exports<'react-redux/src/utils/Subscription'>;
}
declare module 'react-redux/src/utils/verifyPlainObject.js' {
  declare module.exports: $Exports<'react-redux/src/utils/verifyPlainObject'>;
}
declare module 'react-redux/src/utils/warning.js' {
  declare module.exports: $Exports<'react-redux/src/utils/warning'>;
}
declare module 'react-redux/src/utils/wrapActionCreators.js' {
  declare module.exports: $Exports<'react-redux/src/utils/wrapActionCreators'>;
}
