// flow-typed signature: 043b9e600a4bb86b5723d3e1cf000d53
// flow-typed version: <<STUB>>/react-test-renderer_v^15.4.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-test-renderer/lib/accumulate' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/accumulateInto' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/adler32' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/CallbackQueue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/canDefineProperty' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/checkReactTypeSpec' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/deprecated' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/EventConstants' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/EventPluginHub' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/EventPluginRegistry' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/EventPluginUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/EventPropagators' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/flattenChildren' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/forEachAccumulated' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/getHostComponentFromComposite' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/getIteratorFn' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/getNextDebugID' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/instantiateReactComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/isTextInputElement' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/KeyEscapeUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/PluginModuleType' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/PooledClass' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactChildFiber' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactChildReconciler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactComponentEnvironment' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactCompositeComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactCoroutine' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactDebugTool' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactDefaultBatchingStrategy' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactElementSymbol' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactErrorUtils' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactEventEmitterMixin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFeatureFlags' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiber' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberBeginWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberCommitWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberCompleteWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberReconciler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberRoot' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberScheduler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactFiberUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactHostComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactHostOperationHistoryHook' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactInstanceMap' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactInstanceType' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactInstrumentation' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactInvalidSetStateWarningHook' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactMultiChild' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactMultiChildUpdateTypes' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactNodeTypes' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactOwner' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactPerf' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactPriorityLevel' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/reactProdInvariant' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactPropTypeLocationNames' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactPropTypeLocations' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactPropTypesSecret' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactReconciler' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactRef' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactReifiedYield' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactSimpleEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactSyntheticEventType' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTestEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTestMount' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTestReconcileTransaction' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTestRenderer' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTestTextComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTypeOfWork' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactTypes' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactUpdates' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ReactVersion' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ResponderSyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/ResponderTouchHistoryStore' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/shouldUpdateReactComponent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/SyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/TouchHistoryMath' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/Transaction' {
  declare module.exports: any;
}

declare module 'react-test-renderer/lib/traverseAllChildren' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-test-renderer/index' {
  declare module.exports: $Exports<'react-test-renderer'>;
}
declare module 'react-test-renderer/index.js' {
  declare module.exports: $Exports<'react-test-renderer'>;
}
declare module 'react-test-renderer/lib/accumulate.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/accumulate'>;
}
declare module 'react-test-renderer/lib/accumulateInto.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/accumulateInto'>;
}
declare module 'react-test-renderer/lib/adler32.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/adler32'>;
}
declare module 'react-test-renderer/lib/CallbackQueue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/CallbackQueue'>;
}
declare module 'react-test-renderer/lib/canDefineProperty.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/canDefineProperty'>;
}
declare module 'react-test-renderer/lib/checkReactTypeSpec.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/checkReactTypeSpec'>;
}
declare module 'react-test-renderer/lib/deprecated.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/deprecated'>;
}
declare module 'react-test-renderer/lib/EventConstants.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/EventConstants'>;
}
declare module 'react-test-renderer/lib/EventPluginHub.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/EventPluginHub'>;
}
declare module 'react-test-renderer/lib/EventPluginRegistry.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/EventPluginRegistry'>;
}
declare module 'react-test-renderer/lib/EventPluginUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/EventPluginUtils'>;
}
declare module 'react-test-renderer/lib/EventPropagators.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/EventPropagators'>;
}
declare module 'react-test-renderer/lib/flattenChildren.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/flattenChildren'>;
}
declare module 'react-test-renderer/lib/forEachAccumulated.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/forEachAccumulated'>;
}
declare module 'react-test-renderer/lib/getHostComponentFromComposite.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/getHostComponentFromComposite'>;
}
declare module 'react-test-renderer/lib/getIteratorFn.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/getIteratorFn'>;
}
declare module 'react-test-renderer/lib/getNextDebugID.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/getNextDebugID'>;
}
declare module 'react-test-renderer/lib/instantiateReactComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/instantiateReactComponent'>;
}
declare module 'react-test-renderer/lib/isTextInputElement.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/isTextInputElement'>;
}
declare module 'react-test-renderer/lib/KeyEscapeUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/KeyEscapeUtils'>;
}
declare module 'react-test-renderer/lib/PluginModuleType.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/PluginModuleType'>;
}
declare module 'react-test-renderer/lib/PooledClass.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/PooledClass'>;
}
declare module 'react-test-renderer/lib/ReactChildFiber.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactChildFiber'>;
}
declare module 'react-test-renderer/lib/ReactChildReconciler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactChildReconciler'>;
}
declare module 'react-test-renderer/lib/ReactComponentEnvironment.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactComponentEnvironment'>;
}
declare module 'react-test-renderer/lib/ReactCompositeComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactCompositeComponent'>;
}
declare module 'react-test-renderer/lib/ReactCoroutine.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactCoroutine'>;
}
declare module 'react-test-renderer/lib/ReactDebugTool.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactDebugTool'>;
}
declare module 'react-test-renderer/lib/ReactDefaultBatchingStrategy.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactDefaultBatchingStrategy'>;
}
declare module 'react-test-renderer/lib/ReactElementSymbol.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactElementSymbol'>;
}
declare module 'react-test-renderer/lib/ReactEmptyComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactEmptyComponent'>;
}
declare module 'react-test-renderer/lib/ReactErrorUtils.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactErrorUtils'>;
}
declare module 'react-test-renderer/lib/ReactEventEmitterMixin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactEventEmitterMixin'>;
}
declare module 'react-test-renderer/lib/ReactFeatureFlags.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFeatureFlags'>;
}
declare module 'react-test-renderer/lib/ReactFiber.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiber'>;
}
declare module 'react-test-renderer/lib/ReactFiberBeginWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberBeginWork'>;
}
declare module 'react-test-renderer/lib/ReactFiberCommitWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberCommitWork'>;
}
declare module 'react-test-renderer/lib/ReactFiberCompleteWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberCompleteWork'>;
}
declare module 'react-test-renderer/lib/ReactFiberReconciler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberReconciler'>;
}
declare module 'react-test-renderer/lib/ReactFiberRoot.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberRoot'>;
}
declare module 'react-test-renderer/lib/ReactFiberScheduler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberScheduler'>;
}
declare module 'react-test-renderer/lib/ReactFiberUpdateQueue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactFiberUpdateQueue'>;
}
declare module 'react-test-renderer/lib/ReactHostComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactHostComponent'>;
}
declare module 'react-test-renderer/lib/ReactHostOperationHistoryHook.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactHostOperationHistoryHook'>;
}
declare module 'react-test-renderer/lib/ReactInstanceMap.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactInstanceMap'>;
}
declare module 'react-test-renderer/lib/ReactInstanceType.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactInstanceType'>;
}
declare module 'react-test-renderer/lib/ReactInstrumentation.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactInstrumentation'>;
}
declare module 'react-test-renderer/lib/ReactInvalidSetStateWarningHook.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactInvalidSetStateWarningHook'>;
}
declare module 'react-test-renderer/lib/ReactMultiChild.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactMultiChild'>;
}
declare module 'react-test-renderer/lib/ReactMultiChildUpdateTypes.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactMultiChildUpdateTypes'>;
}
declare module 'react-test-renderer/lib/ReactNodeTypes.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactNodeTypes'>;
}
declare module 'react-test-renderer/lib/ReactOwner.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactOwner'>;
}
declare module 'react-test-renderer/lib/ReactPerf.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactPerf'>;
}
declare module 'react-test-renderer/lib/ReactPriorityLevel.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactPriorityLevel'>;
}
declare module 'react-test-renderer/lib/reactProdInvariant.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/reactProdInvariant'>;
}
declare module 'react-test-renderer/lib/ReactPropTypeLocationNames.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactPropTypeLocationNames'>;
}
declare module 'react-test-renderer/lib/ReactPropTypeLocations.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactPropTypeLocations'>;
}
declare module 'react-test-renderer/lib/ReactPropTypesSecret.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactPropTypesSecret'>;
}
declare module 'react-test-renderer/lib/ReactReconciler.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactReconciler'>;
}
declare module 'react-test-renderer/lib/ReactRef.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactRef'>;
}
declare module 'react-test-renderer/lib/ReactReifiedYield.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactReifiedYield'>;
}
declare module 'react-test-renderer/lib/ReactSimpleEmptyComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactSimpleEmptyComponent'>;
}
declare module 'react-test-renderer/lib/ReactSyntheticEventType.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactSyntheticEventType'>;
}
declare module 'react-test-renderer/lib/ReactTestEmptyComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTestEmptyComponent'>;
}
declare module 'react-test-renderer/lib/ReactTestMount.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTestMount'>;
}
declare module 'react-test-renderer/lib/ReactTestReconcileTransaction.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTestReconcileTransaction'>;
}
declare module 'react-test-renderer/lib/ReactTestRenderer.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTestRenderer'>;
}
declare module 'react-test-renderer/lib/ReactTestTextComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTestTextComponent'>;
}
declare module 'react-test-renderer/lib/ReactTypeOfWork.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTypeOfWork'>;
}
declare module 'react-test-renderer/lib/ReactTypes.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactTypes'>;
}
declare module 'react-test-renderer/lib/ReactUpdateQueue.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactUpdateQueue'>;
}
declare module 'react-test-renderer/lib/ReactUpdates.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactUpdates'>;
}
declare module 'react-test-renderer/lib/ReactVersion.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ReactVersion'>;
}
declare module 'react-test-renderer/lib/ResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ResponderEventPlugin'>;
}
declare module 'react-test-renderer/lib/ResponderSyntheticEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ResponderSyntheticEvent'>;
}
declare module 'react-test-renderer/lib/ResponderTouchHistoryStore.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/ResponderTouchHistoryStore'>;
}
declare module 'react-test-renderer/lib/shouldUpdateReactComponent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/shouldUpdateReactComponent'>;
}
declare module 'react-test-renderer/lib/SyntheticEvent.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/SyntheticEvent'>;
}
declare module 'react-test-renderer/lib/TouchHistoryMath.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/TouchHistoryMath'>;
}
declare module 'react-test-renderer/lib/Transaction.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/Transaction'>;
}
declare module 'react-test-renderer/lib/traverseAllChildren.js' {
  declare module.exports: $Exports<'react-test-renderer/lib/traverseAllChildren'>;
}
