// flow-typed signature: bb3fd5fefd68614e0af925fe65f50a8d
// flow-typed version: <<STUB>>/redux-logger_v^2.7.4/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-logger/dist/index' {
  declare module.exports: any;
}

declare module 'redux-logger/dist/index.min' {
  declare module.exports: any;
}

declare module 'redux-logger/lib/core' {
  declare module.exports: any;
}

declare module 'redux-logger/lib/defaults' {
  declare module.exports: any;
}

declare module 'redux-logger/lib/diff' {
  declare module.exports: any;
}

declare module 'redux-logger/lib/helpers' {
  declare module.exports: any;
}

declare module 'redux-logger/lib/index' {
  declare module.exports: any;
}

declare module 'redux-logger/src/core' {
  declare module.exports: any;
}

declare module 'redux-logger/src/defaults' {
  declare module.exports: any;
}

declare module 'redux-logger/src/diff' {
  declare module.exports: any;
}

declare module 'redux-logger/src/helpers' {
  declare module.exports: any;
}

declare module 'redux-logger/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-logger/dist/index.js' {
  declare module.exports: $Exports<'redux-logger/dist/index'>;
}
declare module 'redux-logger/dist/index.min.js' {
  declare module.exports: $Exports<'redux-logger/dist/index.min'>;
}
declare module 'redux-logger/lib/core.js' {
  declare module.exports: $Exports<'redux-logger/lib/core'>;
}
declare module 'redux-logger/lib/defaults.js' {
  declare module.exports: $Exports<'redux-logger/lib/defaults'>;
}
declare module 'redux-logger/lib/diff.js' {
  declare module.exports: $Exports<'redux-logger/lib/diff'>;
}
declare module 'redux-logger/lib/helpers.js' {
  declare module.exports: $Exports<'redux-logger/lib/helpers'>;
}
declare module 'redux-logger/lib/index.js' {
  declare module.exports: $Exports<'redux-logger/lib/index'>;
}
declare module 'redux-logger/src/core.js' {
  declare module.exports: $Exports<'redux-logger/src/core'>;
}
declare module 'redux-logger/src/defaults.js' {
  declare module.exports: $Exports<'redux-logger/src/defaults'>;
}
declare module 'redux-logger/src/diff.js' {
  declare module.exports: $Exports<'redux-logger/src/diff'>;
}
declare module 'redux-logger/src/helpers.js' {
  declare module.exports: $Exports<'redux-logger/src/helpers'>;
}
declare module 'redux-logger/src/index.js' {
  declare module.exports: $Exports<'redux-logger/src/index'>;
}
