// flow-typed signature: e1c86c6119074f0d772af793b7260efa
// flow-typed version: <<STUB>>/redux-thunk_v^2.1.0/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-thunk/dist/redux-thunk' {
  declare module.exports: any;
}

declare module 'redux-thunk/dist/redux-thunk.min' {
  declare module.exports: any;
}

declare module 'redux-thunk/es/index' {
  declare module.exports: any;
}

declare module 'redux-thunk/lib/index' {
  declare module.exports: any;
}

declare module 'redux-thunk/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-thunk/dist/redux-thunk.js' {
  declare module.exports: $Exports<'redux-thunk/dist/redux-thunk'>;
}
declare module 'redux-thunk/dist/redux-thunk.min.js' {
  declare module.exports: $Exports<'redux-thunk/dist/redux-thunk.min'>;
}
declare module 'redux-thunk/es/index.js' {
  declare module.exports: $Exports<'redux-thunk/es/index'>;
}
declare module 'redux-thunk/lib/index.js' {
  declare module.exports: $Exports<'redux-thunk/lib/index'>;
}
declare module 'redux-thunk/src/index.js' {
  declare module.exports: $Exports<'redux-thunk/src/index'>;
}
