// flow-typed signature: 1e5f35a09e3445cc14a44a645545f814
// flow-typed version: <<STUB>>/sass-loader_v^6.0.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass-loader/lib/formatSassError' {
  declare module.exports: any;
}

declare module 'sass-loader/lib/importsToResolve' {
  declare module.exports: any;
}

declare module 'sass-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'sass-loader/lib/normalizeOptions' {
  declare module.exports: any;
}

declare module 'sass-loader/lib/proxyCustomImporters' {
  declare module.exports: any;
}

declare module 'sass-loader/lib/webpackImporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sass-loader/lib/formatSassError.js' {
  declare module.exports: $Exports<'sass-loader/lib/formatSassError'>;
}
declare module 'sass-loader/lib/importsToResolve.js' {
  declare module.exports: $Exports<'sass-loader/lib/importsToResolve'>;
}
declare module 'sass-loader/lib/loader.js' {
  declare module.exports: $Exports<'sass-loader/lib/loader'>;
}
declare module 'sass-loader/lib/normalizeOptions.js' {
  declare module.exports: $Exports<'sass-loader/lib/normalizeOptions'>;
}
declare module 'sass-loader/lib/proxyCustomImporters.js' {
  declare module.exports: $Exports<'sass-loader/lib/proxyCustomImporters'>;
}
declare module 'sass-loader/lib/webpackImporter.js' {
  declare module.exports: $Exports<'sass-loader/lib/webpackImporter'>;
}
