// flow-typed signature: f2c93e6623b9d49179690c4d96cb0276
// flow-typed version: <<STUB>>/spectron_v^3.4.0/flow_v0.37.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spectron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'spectron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spectron/lib/accessibility' {
  declare module.exports: any;
}

declare module 'spectron/lib/api' {
  declare module.exports: any;
}

declare module 'spectron/lib/application' {
  declare module.exports: any;
}

declare module 'spectron/lib/chrome-driver' {
  declare module.exports: any;
}

declare module 'spectron/lib/launcher' {
  declare module.exports: any;
}

declare module 'spectron/vendor/axs_testing' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spectron/index' {
  declare module.exports: $Exports<'spectron'>;
}
declare module 'spectron/index.js' {
  declare module.exports: $Exports<'spectron'>;
}
declare module 'spectron/lib/accessibility.js' {
  declare module.exports: $Exports<'spectron/lib/accessibility'>;
}
declare module 'spectron/lib/api.js' {
  declare module.exports: $Exports<'spectron/lib/api'>;
}
declare module 'spectron/lib/application.js' {
  declare module.exports: $Exports<'spectron/lib/application'>;
}
declare module 'spectron/lib/chrome-driver.js' {
  declare module.exports: $Exports<'spectron/lib/chrome-driver'>;
}
declare module 'spectron/lib/launcher.js' {
  declare module.exports: $Exports<'spectron/lib/launcher'>;
}
declare module 'spectron/vendor/axs_testing.js' {
  declare module.exports: $Exports<'spectron/vendor/axs_testing'>;
}
