// flow-typed signature: be6f7d69bab2ee86c971763b42e9b0db
// flow-typed version: <<STUB>>/webpack-dev-middleware_v^1.8.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-middleware/lib/GetFilenameFromUrl' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/lib/PathJoin' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/lib/Shared' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-middleware/lib/GetFilenameFromUrl.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/lib/GetFilenameFromUrl'>;
}
declare module 'webpack-dev-middleware/lib/PathJoin.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/lib/PathJoin'>;
}
declare module 'webpack-dev-middleware/lib/Shared.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/lib/Shared'>;
}
declare module 'webpack-dev-middleware/middleware.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/middleware'>;
}
