// flow-typed signature: d2f488177de885ecabbc784d16468fd5
// flow-typed version: <<STUB>>/webpack-dev-server_v^2.4.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-server/bin/webpack-dev-server' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/index.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/index' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/live.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/live' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/overlay' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/socket' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/sockjs.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/sockjs' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/web_modules/jquery/index' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/web_modules/jquery/jquery-1.8.1' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/webpack.sockjs.config' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/OptionsValidationError' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/Server' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/util/addDevServerEntrypoints' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/util/createDomain' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-server/bin/webpack-dev-server.js' {
  declare module.exports: $Exports<'webpack-dev-server/bin/webpack-dev-server'>;
}
declare module 'webpack-dev-server/client/index.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/index.bundle'>;
}
declare module 'webpack-dev-server/client/index.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/index'>;
}
declare module 'webpack-dev-server/client/live.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/live.bundle'>;
}
declare module 'webpack-dev-server/client/live.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/live'>;
}
declare module 'webpack-dev-server/client/overlay.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/overlay'>;
}
declare module 'webpack-dev-server/client/socket.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/socket'>;
}
declare module 'webpack-dev-server/client/sockjs.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/sockjs.bundle'>;
}
declare module 'webpack-dev-server/client/sockjs.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/sockjs'>;
}
declare module 'webpack-dev-server/client/web_modules/jquery/index.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/web_modules/jquery/index'>;
}
declare module 'webpack-dev-server/client/web_modules/jquery/jquery-1.8.1.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/web_modules/jquery/jquery-1.8.1'>;
}
declare module 'webpack-dev-server/client/webpack.config.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/webpack.config'>;
}
declare module 'webpack-dev-server/client/webpack.sockjs.config.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/webpack.sockjs.config'>;
}
declare module 'webpack-dev-server/lib/OptionsValidationError.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/OptionsValidationError'>;
}
declare module 'webpack-dev-server/lib/Server.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/Server'>;
}
declare module 'webpack-dev-server/lib/util/addDevServerEntrypoints.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/util/addDevServerEntrypoints'>;
}
declare module 'webpack-dev-server/lib/util/createDomain.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/util/createDomain'>;
}
