// flow-typed signature: 120f34f625f7d493bfaf70e8761ae58b
// flow-typed version: <<STUB>>/webpack-hot-middleware_v^2.15.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-hot-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-hot-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-hot-middleware/client-overlay' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/client' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/example/client' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/example/extra' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/example/server' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/example/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/example/webpack.config.multientry' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/helpers' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/middleware' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/process-update' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/test/client-test' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/test/helpers-test' {
  declare module.exports: any;
}

declare module 'webpack-hot-middleware/test/middleware-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-hot-middleware/client-overlay.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/client-overlay'>;
}
declare module 'webpack-hot-middleware/client.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/client'>;
}
declare module 'webpack-hot-middleware/example/client.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/example/client'>;
}
declare module 'webpack-hot-middleware/example/extra.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/example/extra'>;
}
declare module 'webpack-hot-middleware/example/server.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/example/server'>;
}
declare module 'webpack-hot-middleware/example/webpack.config.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/example/webpack.config'>;
}
declare module 'webpack-hot-middleware/example/webpack.config.multientry.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/example/webpack.config.multientry'>;
}
declare module 'webpack-hot-middleware/helpers.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/helpers'>;
}
declare module 'webpack-hot-middleware/middleware.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/middleware'>;
}
declare module 'webpack-hot-middleware/process-update.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/process-update'>;
}
declare module 'webpack-hot-middleware/test/client-test.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/test/client-test'>;
}
declare module 'webpack-hot-middleware/test/helpers-test.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/test/helpers-test'>;
}
declare module 'webpack-hot-middleware/test/middleware-test.js' {
  declare module.exports: $Exports<'webpack-hot-middleware/test/middleware-test'>;
}
