export const SET_EDITOR_CONTENT = 'SET_EDITOR_CONTENT';
export const SET_EDITOR_PATH = 'SET_EDITOR_PATH';

export const SET_EXPLORER_CONTENT = 'SET_EXPLORER_CONTENT';

export const SET_HOST_NAME = 'SET_HOST_NAME';
export const SET_FTP_PORT = 'SET_FTP_PORT';
export const SET_FTP_USER_NAME = 'SET_FTP_USER_NAME';
export const SET_FTP_PASSWORD = 'SET_FTP_PASSWORD';

export const SET_THEME_DARK = 'SET_THEME_DARK';
export const SET_THEME_LIGHT = 'SET_THEME_LIGHT';
export const SET_COLOR = 'SET_COLOR';

export const SET_RESULTS_CONTENT = 'SET_RESULTS_CONTENT';
export const SET_JOB_STATUS = 'SET_JOB_STATUS';
export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const SET_IS_CONNECTED = 'SET_IS_CONNECTED';
export const SET_IS_CONNECTING = 'SET_IS_CONNECTING';
export const SET_IS_RETRIEVED = 'SET_IS_RETRIEVED';
export const SET_IS_RETRIEVING = 'SET_IS_RETRIEVING';
export const SET_IS_SUBMITTED = 'SET_IS_SUBMITTED';
export const SET_IS_SUBMITTING = 'SET_IS_SUBMITTING';
export const SET_IS_DISCONNECTED = 'SET_IS_DISCONNECTED';
export const SET_IS_DISCONNECTING = 'SET_IS_DISCONNECTING';


export const REFRESH_JOBS = 'REFRESH_JOBS';
export const LOAD_JOB_RESULTS = 'LOAD_JOB_RESULTS';

export const REFRESH_DATASETS = 'REFRESH_DATASETS';