import {
  FROM_1_TO_60_REGEX,
  FROM_1_TO_2K_REGEX,
  FROM_1_TO_10K_REGEX,
  FROM_1_TO_3K_REGEX,
  FROM_1_TO_18K_REGEX,
  FROM_0001_TO_100_REGEX,
  FROM_1_TO_10_REGEX,
  FROM_1_TO_9999_REGEX,
} from 'utils/constants';
import { auxActionParamsCode } from 'pages/Contour/interface';

export const actionParams: auxActionParamsCode[] = [
  {
    actionCode: 'M3',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_2K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M4',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_2K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M11',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_60_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M13',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_2K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M14',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_2K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M31',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_60_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M37',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_60_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M51',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_10K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M57',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_60_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M103',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_2K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M104',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_2K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M111',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_3K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M112',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_18K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M113',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_2K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M114',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_2K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M131',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_18K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M151',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_10K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'M218',
    param1Id: 'S',
    param1Value: '',
    param1Validation: FROM_1_TO_10K_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'G2',
    param1Id: 'R',
    param1Value: '',
    param1Validation: FROM_0001_TO_100_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'G3',
    param1Id: 'R',
    param1Value: '',
    param1Validation: FROM_0001_TO_100_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'G4.1',
    param1Id: 'P1',
    param1Value: '',
    param1Validation: null,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'G31',
    param1Id: 'P',
    param1Value: '',
    param1Validation: FROM_1_TO_10_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  {
    actionCode: 'G65',
    param1Id: 'P',
    param1Value: '',
    param1Validation: FROM_1_TO_9999_REGEX,
    param2Id: '',
    param2Value: null,
    param2Validation: null,
    param3Id: '',
    param3Value: null,
    param3Validation: null,
  },
  // test case
  {
    actionCode: 'G121',
    param1Id: 'A',
    param1Value: '',
    param1Validation: FROM_1_TO_9999_REGEX,
    param2Id: 'M',
    param2Value: '',
    param2Validation: FROM_1_TO_9999_REGEX,
    param3Id: 'S',
    param3Value: '',
    param3Validation: FROM_1_TO_9999_REGEX,
  },
];
