import {
  FROM_1_TO_60_REGEX,
  FROM_1_TO_2K_REGEX,
  FROM_1_TO_10K_REGEX,
  FROM_1_TO_3K_REGEX,
  FROM_1_TO_18K_REGEX,
  FROM_0001_TO_100_REGEX,
  FROM_1_TO_10_REGEX,
  FROM_1_TO_9999_REGEX,
} from 'utils/constants';
import { auxActionParamsCode } from 'pages/Contour/interface';

export const actionParams: auxActionParamsCode[] = [
  {
    actionCode: 'M3',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_2K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M4',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_2K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M11',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_60_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M13',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_2K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M14',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_2K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M31',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_60_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M37',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_60_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M51',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_10K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M57',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_60_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M103',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_2K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M104',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_2K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M111',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_3K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M112',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_18K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M113',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_2K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M114',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_2K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M131',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_18K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M151',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_10K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'M218',
    aParamId: 'S',
    aParamValue: '',
    aParamValidation: FROM_1_TO_10K_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'G2',
    aParamId: 'R',
    aParamValue: '',
    aParamValidation: FROM_0001_TO_100_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'G3',
    aParamId: 'R',
    aParamValue: '',
    aParamValidation: FROM_0001_TO_100_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'G4.1',
    aParamId: 'P1',
    aParamValue: '',
    aParamValidation: null,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'G31',
    aParamId: 'P',
    aParamValue: '',
    aParamValidation: FROM_1_TO_10_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  {
    actionCode: 'G65',
    aParamId: 'P',
    aParamValue: '',
    aParamValidation: FROM_1_TO_9999_REGEX,
    bParamId: '',
    bParamValue: null,
    bParamValidation: null,
    cParamId: '',
    cParamValue: null,
    cParamValidation: null,
  },
  // test case
  {
    actionCode: 'G121',
    aParamId: 'A',
    aParamValue: '',
    aParamValidation: FROM_1_TO_9999_REGEX,
    bParamId: 'M',
    bParamValue: '',
    bParamValidation: FROM_1_TO_9999_REGEX,
    cParamId: 'S',
    cParamValue: '',
    cParamValidation: FROM_1_TO_9999_REGEX,
  },
];
